### ISSUE TITLE
List of all blog posts #1

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/code-challenge#1]
#### Acceptance Criteria

- [X] All blog posts are displayed as a list 📖
- [X] A header with a headline is displayed 
- [X] Creation date should be displayed user friendly

#### Tasks

- [X] fetch data from: http://localhost:3001/rest/blogposts
- [X] Create the component `Header` with props `headline`
- [X] use index.js which renders the Component `Blogposts` and `Header`
- [X] Create the component `Blogposts` to render a list of all posts
- [X] displayed details are: `title`, `created`, `content`
- [X] use .toLocaleDateString fro displaying the date
