### ISSUE TITLE
Details page #2

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/code-challenge#2]
#### Acceptance Criteria

- [X] One detail page for each blogpost is displayed
- [X] Each page contains: `title`, `subtitle`, `created`, `image`,`author`, `content`
- [X] clicking on the blog post on the homepage leads to the respective details page 
- [X] A back button is displayed to navigate to the previous page
- [X] A header is displayed

#### Tasks

- [X] Render the Component `BlogpostDetails`
- [X] Create the page pages/[name] that renders the component `BlogpostDetails`
- [X] add useRouter for Navigation through the pages 
- [X] Add a back Button which leads to the previous page
- [X] on component `Blogposts` a link routes to the respective details page when clicking on the countries name
