### ISSUE TITLE
Link to share #3

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/code-challenge#3]
#### Acceptance Criteria

- [X] Buttons are displayed on every blog post
- [X] Clicking on the symbol allows the user to send the link to a friend
- [X] When the link is copied to the clipboard a text appears to let the user know it worked

#### Tasks

- [X] Display a button for copying the link to the clipboard
- [X] Display a button for sharing the link via WhatsApp
- [X] Display a button for sharing the link via Mail
- [X] Create the Component `SharingButtons`
- [X] use `useState` to display a text when condition `isCopied` is true
